default: &default
  primary:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  kooragang:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["KOORAGANG_DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    migrations_paths: <%= Rails.root %>/db/kooragang_migrate

development:
  <<: *default
test:
  <<: *default
